# https://embassy.dev/book/dev/faq.html#_my_binary_is_still_big_filled_with_stdfmt_stuff
# [unstable]
# build-std = ["core"]
# build-std-features = ["panic_immediate_abort"]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# probe-rs is used for defmt logging
# probe-run --list-chips | grep G030
runner = "probe-rs run --chip STM32G030K6Tx"

rustflags = [
  # LLD (shipped with the Rust toolchain) is used as the default linker
  "-C",
  "link-arg=-Tlink.x",
  "-C",
  "link-arg=-Tdefmt.x",
  # This is needed if your flash or ram addresses are not aligned to 0x10000 in memory.x
  # See https://github.com/rust-embedded/cortex-m-quickstart/pull/95
  "-C",
  "link-arg=--nmagic",
]

[build]
target = "thumbv6m-none-eabi" # Cortex-M0 and Cortex-M0+

[net]
git-fetch-with-cli = true

[alias]
rb = "run --bin"
rrb = "run --release --bin"

[env]
DEFMT_LOG = "info"
